

select
 ESIB.ITEM_NUMBER,
 ESIB.INVENTORY_ITEM_STATUS_CODE,
 ESIB.INVENTORY_ORGANIZATION_ID,
 ESIB.INVENTORY_ITEM_ID , 
 ESIB.ITEM_CATALOG_GROUP_ID ,
 ESIB.BOM_ITEM_TYPE ,
 ESIB.WIP_SUPPLY_TYPE ,
 ESIB.PRIMARY_UOM_CODE ,
 ESIB.COSTING_ENABLED_FLAG ,
 ESIB.ITEM_TYPE ,
 ESIB.APPROVAL_STATUS ,
 
 ESIB.CREATED_BY ,
 ESIB.ORGANIZATION_ID , 
 ESIT.DESCRIPTION, 
 EIRB.REVISION_ID ,
 EIRB.REVISION ,

  HOU.EFFECTIVE_START_DATE ,
  HOU.EFFECTIVE_END_DATE,
   HOU.BUSINESS_GROUP_ID  ,
   HOU.NAME ,
   HOU.LOCATION_ID,
   
   HOC.ORG_UNIT_CLASSIFICATION_ID ,
   HOC.CLASSIFICATION_CODE ,
   
   INVP.ORGANIZATION_CODE ,
   INVP.MASTER_ORGANIZATION_ID ,
  INVP.SCHEDULE_ID ,
   INVP.BUSINESS_UNIT_ID ,
   INVP.STOCK_LOCATOR_CONTROL_CODE ,
   INVP.SERIAL_NUMBER_TYPE ,
   INVP.LOT_NUMBER_UNIQUENESS ,
   INVP.SERIAL_NUMBER_GENERATION ,
   INVP.ITEM_GROUPING_CODE ,
   INVP.ITEM_DEFINITION_ORG_ID,   
   FB.BU_ID,
      FB.BU_NAME ,
	  	 FB.PRIMARY_LEDGER_ID ,
	  FB.DEFAULT_CURRENCY_CODE ,	  
GL.LEDGER_ID ,
	 GL.NAME LEDGERNAME ,
	  GL.DESCRIPTION LEDERDES ,
	  GL.LEDGER_CATEGORY_CODE ,
	  GL.LE_LEDGER_TYPE_CODE ,
	  GL.COMPLETION_STATUS_CODE ,
	  GL.CONFIGURATION_ID ,
	  GL.CHART_OF_ACCOUNTS_ID ,
	  GL.CURRENCY_CODE ,
	  GL.ACCOUNTED_PERIOD_TYPE ,
	  GL.CUM_TRANS_CODE_COMBINATION_ID ,
	  GL.SEQUENCING_MODE_CODE,
      GL.OBJECT_TYPE_CODE,
      GL.COMPLETE_FLAG  
 from EGP_SYSTEM_ITEMS_B ESIB,
 
 EGP_SYSTEM_ITEMS_TL ESIT,
 
EGP_ITEM_REVISIONS_B EIRB,

HR_ALL_ORGANIZATION_UNITS_X HOU,

HR_ORG_UNIT_CLASSIFICATIONS_X HOC,

INV_ORG_PARAMETERS INVP,

FUN_ALL_BUSINESS_UNITS_V FB,

GL_LEDGERS GL

WHERE ESIB.INVENTORY_ITEM_ID=ESIT.INVENTORY_ITEM_ID

AND ESIB.INVENTORY_ITEM_ID=EIRB.INVENTORY_ITEM_ID

AND HOU.ORGANIZATION_ID = HOC.ORGANIZATION_ID

AND HOU.ORGANIZATION_ID = INVP.ORGANIZATION_ID

AND HOC.CLASSIFICATION_CODE = 'INV'

AND FB.PRIMARY_LEDGER_ID = GL.LEDGER_ID(+)

AND GL.OBJECT_TYPE_CODE(+) = 'L'

AND NVL(GL.COMPLETE_FLAG, 'Y') = 'Y'

AND FB.BUSINESS_GROUP_ID(+) = INVP.BUSINESS_UNIT_ID

 
	   
	   
	   